# Generated by Django 4.2.4 on 2023-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
