# Generated by Django 4.2.4 on 2023-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='habitentry',
            unique_together={('habit', 'entry_date')},
        ),
    ]
