# Generated by Django 4.2.4 on 2023-09-06 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0005_alter_habitentry_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.PositiveIntegerField(help_text="If you select 'Check' as the units, the goal will be set to 1 automatically."),
        ),
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(default=True)),
                ('can_interact', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
