# Generated by Django 4.2.4 on 2023-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_goal_demouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='demo_user_can_interact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demouser',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
